language: node_js
node_js:
 - "6.11.2"

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g bower grunt-cli@1.2.0
 - npm install --quiet
 - bower cache clean
 - bower install --verbose

script: grunt karma:unit
